### ISSUE TITLE
Sanity.io requires an empty directory

### ISSUE THREAD

**Issue by frankstallone** [sanity-io/sanity-template-astro-clean#12]
First, I followed your tutorial and am very grateful for it! I love Astro, and still on the fence about Sanity.io. I have been trying to find a better solution than WordPress for years now in the JS world for my clients that need performant marketing sites. It's closer than it's ever been but the complexities have always made it unbearable. 

I created a site doing a similar set up to yours and wanted to create a template out of it. However, I ran into an issue that happens in your repo too. If I clone your repo here and get to step 2 and run `npm create sanity@latest init --env` — it asks for an empty directory. However, your directory is not empty. 

This leads me to two thoughts. One, how does anyone create their own Sanity.io template with regards to `schema`, for instance, when you have to start with an empty directory? 

I just noticed you [worked on a few of these templates](https://www.sanity.io/templates). They will all have the same issue with step 2. What have you found to be the best practice here, delete the contents of the `/studio` folder first?

**Comment by Nmans01** [comment]
+1 I don't really understand what the intention was here

**Comment by kmelve** [comment]
I believe the command is wrong, it should be `npx sanity@latest init --env`. Then it will work as intended, and you can continue adding to the schema without having to delete the studio folder.
