### ISSUE TITLE
sanity@latest init --env omits "STUDIO" from variable name

### ISSUE THREAD

**Issue by kylehadland** [sanity-io/sanity-template-astro-clean#24]
From terminal logs: 

```
Detected framework Astro, using prefix 'PUBLIC_'
Appended PUBLIC_SANITY_PROJECT_ID="xxxxxxxx"
Appended PUBLIC_SANITY_DATASET="production"
```

Should be PUBLIC_SANITY_STUDIO_PROJECT_ID and PUBLIC_SANITY_STUDIO_DATASET.

Works as expected once manually renamed.

**Comment by kmelve** [comment]
Thanks for reporting! It seems like we have a lot of different environment keys floating around (what's generated by the CLI versus what's generated by Vercel). 

For now, I just added the Vercel keys as a fallback in https://github.com/sanity-io/sanity-template-astro-clean/pull/25.
