### ISSUE TITLE
README: Rename the variables in the .env file

### ISSUE THREAD

**Issue by kerns** [sanity-io/sanity-template-astro-clean#27]
![Screenshot 2023-09-22 at 09 44 02](https://github.com/sanity-io/sanity-template-astro-clean/assets/20254/c32b87a3-68d4-4dba-986a-52f2ecc9960d)

I am not sure the above instructions align with vars set in the .env file after running `npx sanity@latest init --env`.

When I run this my .env ends up with...

PUBLIC_SANITY_PROJECT_ID="xxxxxxxx"
PUBLIC_SANITY_DATASET="production"

Question or issue is with the lack of `_STUDIO_` as part of this variable. Might not be important, or might be something I've misunderstood, just seemed odd.

**Comment by christianhg** [comment]
Hi! I've now removed this bit from the README since it's unneeded. The CLI seems to create env vars with correct names, so no need to rename them: https://github.com/sanity-io/sanity-template-astro-clean/pull/47
