### ISSUE TITLE
This template isn't working for persons with Astro 4

### ISSUE THREAD

**Issue by narration-sd** [sanity-io/sanity-template-astro-clean#37]
The template builds and operates as-is, but when persons upgrade it to use latest packages, including Astro 4 and @sanity/astro to accompany that, there are multiple failures.

To reproduce, run `ncu -u` from the top folder, and then attempt `npm run dev`, or `npm run build`. 

Expected, is that with current packages, the template should just work.

I've created a fork with upgrades to fit the current software, available on branch main to make it easy to use. I'm not presenting a PR for these yet, because they necessarily use a temporarily published upgrade of `@sanity/astro`, on `@narration-sd/santy-astro`.

When its PR for official `@sanity/astro` resolves, I'll update the fork, and PR this repo for a completed result, reporting again here also.

**Comment by vmitsaras** [comment]
https://github.com/narration-sd/sanity-template-astro-clean
Is there any progress being made towards a merge?

**Comment by narration-sd** [comment]
Hi Vaslis @vmitsaras, in fact I've just last night released the PR here: #40. 

You can work from [the upgraded version](https://github.com/narration-sd/sanity-template-astro-clean) for now which others have, as I think it's pretty solid. 

This offers a much nicer experience I think, beside including Astro 4, along with all dependencies at latest code date up to now.

**Comment by christianhg** [comment]
Hi! Sorry about that! I've now made sure to upgrade the dependencies used by this template.
