### ISSUE TITLE
Build Fails on Vercel When Adding Post To Content Collection

### ISSUE THREAD

**Issue by AdamGEmerson** [sanity-io/sanity-template-astro-clean#43]
**Describe the bug**

Deploying the template on vercel results in failed builds due to in invalid runtime for Vercel Serverless Functions.

**To Reproduce**

1. Use the "Deploy with Vercel" button to launch the template.

<img width="441" alt="Screenshot 2024-03-20 at 3 58 28 AM" src="https://github.com/sanity-io/sanity-template-astro-clean/assets/35545129/636e15b3-c606-4610-988d-cb723433f4a9">
  
2. Follow the steps for setup as written in the template
3. Create a new post.
4. Commit to github to trigger Vercel redeploy or redeploy manually.
5. Build fails with error:

<img width="1249" alt="Screenshot 2024-03-20 at 4 00 07 AM" src="https://github.com/sanity-io/sanity-template-astro-clean/assets/35545129/757b2a72-cec7-48c2-bd0f-486a583a6281">

**Expected behavior**

Build should succeed when adding a sample post to the content collection per the template instructions.

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**
```
@sanity/cli (global)  3.17.0 (latest: 3.35.0)
@sanity/astro          1.3.0 (latest: 3.0.0)
@sanity/image-url      1.0.2 (up to date)
@sanity/types         3.17.0 (latest: 3.35.0)
@sanity/vision        3.17.0 (latest: 3.35.0)
sanity                3.17.0 (latest: 3.35.0)
```

**Which versions of Node.js / npm are you running?**

```
10.2.4
v18.19.1
```

** Proposed Solution ** 

This issue resolved for me by updating the `package.json` to have a more current version of node in the `engines` section.

```
"engines": {
    "node": "18"
  }
 ```

**Comment by realitydesigners** [comment]
I'm also getting this error but the proposed solution did not fix it for me

**Comment by AdamGEmerson** [comment]
Hey @realitydesigners, did you ever come to a solution? 

What version of node are you running?

**Comment by christianhg** [comment]
Hi! I've updated the dependencies, including `@astrojs/vercel`, and deployments seem to work again, at least in this repo. Could you try again and let us know if the problem persists?
